### PR TITLE
Added checkbox for documentation changes in template

### PR DESCRIPTION
**Pull request by DunklesArchipel**
…he code.

Checklist
* [x] Added an entry in `doc/news/`. Not required 
* [x] Added a test for this change. Not required

Changes the GitHub template for a PR, asking to verify that no changes are required in the documentation.

### CODE REVIEW

**Comment by saraedum** [comment]
> …he code.

?

**Review by saraedum — APPROVED** [review]

**Comment by saraedum** [comment]
Should we do the same for the other projects?

**Comment by DunklesArchipel** [comment]
> > …he code.
> 
> ?

🤷

**Comment by DunklesArchipel** [comment]
> Should we do the same for the other projects?

I think it is a good reminder. For big changes one can always refer to a new issue.

**Pull request merged**
